config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/' => 'homes#top'
  resources :todolists
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController
  def new
    @list = List.new
  end

  def create
    list = List.new(list_params)
    list.save
    redirect_to '/'
  end

  def index
    @lists = List.all.order("id DESC")
  end

  def show
    @list = List.find(params[:id])
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    list = List.find(params[:id])
    list.update(list_params)
    redirect_to '/todolists'
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to '/todolists'
  end

  private

  def list_params
    params.require(:list).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/todolists_helper.rb
module TodolistsHelper
end

app/views/homes/top.html.erb
<html>
  <header>
    <h1>転職成功への道のり</h1>
  </header>
  <body>
    <div class="container">
      <div class="row">
        <div class="profile">
          <h2>自己紹介</h2>
          <li>
            名前: 久須 隆太郎
          </li>
          <li>
            生年月日: 1997年12月23日（満23歳）
          </li>
          <li>
            趣味: バイクに乗ること
          </li>
        </div>
        <div class="history">
          <h4>前職の経験</h4>
          <p>2020年に甲南大学を卒業後、「人と話すことが好き」「実力主義の会社で若くして稼ぎたい」という理由から<br />
          株式会社プレサンスコーポレーションに入社。<br />
          主な業務としては、電話営業による新規開拓・商談・契約・顧客のアフターフォローを行っておりました。<br />
          教育制度としてOJTを採用している会社だったので入社後すぐ現場で働かせていただきたくさんのお客様とお会いさせていただきました。
          <br />前職は創業社長が1代で、全国で２番目にマンションを売る会社にまで成長したため、新規獲得の営業ノウハウや
          競合他社との差別化などたくさんのことを学ばせていただきました。</p>
        </div>
        <div class="reasons">
          <h4>転職しようと決めた理由・エンジニアになりたいと思った理由</h4>
        </div>
        <div class="todolist">
          <h3>転職のためにすることリスト</h3>
            <li><a href="/todolists/new">追加</a></li>
            <li><a href="/todolists">一覧</a></li>
        </div>
        <div class="portfolio">
          <h3>成果物リスト</h3>
          
          <li><%= link_to "Bikers", "http://52.68.109.146" %></li>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prototype</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todolists/edit.html.erb
<h2>すること内容の変更</h2>
<%= form_with model:@list, url:"/todolists/#{@list.id}", local:true do |f| %>
  <p>題名</p>
  <%= f.text_field :title %>
  <p>本文</p>
  <%= f.text_area :body %>
  <%= f.submit '変更完了' %>
<% end %>
<%= link_to "戻る", :back  %>

app/views/todolists/index.html.erb
<div class="post-index">
  <h1>すること一覧</h1>
  <% @lists.each do |list| %>
    <p>題名</p>
    <span><%= link_to list.title, "/todolists/#{list.id}" %></span>
  <% end %>

</div>
<%= link_to "戻る", "/"  %>

app/views/todolists/new.html.erb
<div class="post-new">
  <h1>新規投稿</h1>
  <%= form_with model:@list, url:'/todolists', local:true do |f| %>
    <h4>題名</h4>
    <%= f.text_field :title %>
    <h4>本文</h4>
    <%= f.text_area :body %>
    <%= f.submit '投稿' %>
  <% end %>
</div>
<%= link_to "戻る", "/"  %>

app/views/todolists/show.html.erb
<div class="post-show">
  <h2>やることの詳細</h2>
  <h4>題名</h4>
  <p><%= @list.title %></p>
  <h4>本文</h4>
  <p><%= @list.body %></p>

  <%= link_to '内容変更', edit_todolist_path(@list.id) %>
  <%= link_to '削除', todolist_path(@list.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>
  <%= link_to "戻る", :back  %>
</div>